/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.swingstoresystem;

/**
 *
 * @author Acer
 */
public class MainSystem extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainSystem.class.getName());
    
    private DataService service = new DataService();
   
    private void updateTotal() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) UnitTable.getModel();
        double GrandTotal = 0;
        for (int i = 0; i < model.getRowCount(); i++ ) {
            GrandTotal += (Double) model.getValueAt(i, 3);
        }
        jLabel2.setText("Total: ₱" + String.format("%.2f", GrandTotal) );
    }
    
    private void populateProductList(){
        javax.swing.DefaultListModel<String> listModel = new javax.swing.DefaultListModel<>();
        Information[] inventory = service.getInventory();
        int count = service.getInventoryCount();
        
        for (int i = 0; i < count; i++) {
            listModel.addElement(inventory[i].getProductName());
        }
        jList1.setModel(listModel);
    }
    
    public MainSystem() {
        initComponents();
        populateProductList();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        CartPanel = new javax.swing.JPanel();
        jscrollpane1 = new javax.swing.JScrollPane();
        UnitTable = new javax.swing.JTable();
        TotalPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ProductsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        QuantityLabel = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnInventory = new javax.swing.JButton();
        btnTransaction = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        CheckoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Store System");
        getContentPane().setLayout(new java.awt.BorderLayout(15, 15));

        CartPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Cart"));
        CartPanel.setLayout(new java.awt.BorderLayout());

        UnitTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Unit Price", "Qty", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jscrollpane1.setViewportView(UnitTable);
        if (UnitTable.getColumnModel().getColumnCount() > 0) {
            UnitTable.getColumnModel().getColumn(0).setResizable(false);
            UnitTable.getColumnModel().getColumn(1).setResizable(false);
            UnitTable.getColumnModel().getColumn(2).setResizable(false);
            UnitTable.getColumnModel().getColumn(3).setResizable(false);
        }

        CartPanel.add(jscrollpane1, java.awt.BorderLayout.CENTER);

        TotalPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Total: ₱");
        TotalPanel.add(jLabel2);

        CartPanel.add(TotalPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(CartPanel, java.awt.BorderLayout.CENTER);

        ProductsPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Products"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        ProductsPanel.setPreferredSize(new java.awt.Dimension(250, 248));
        ProductsPanel.setLayout(new java.awt.BorderLayout());

        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jList1);

        ProductsPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        QuantityLabel.setText("Quantity:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel2.add(QuantityLabel, gridBagConstraints);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinner1.setPreferredSize(new java.awt.Dimension(65, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel2.add(jSpinner1, gridBagConstraints);

        jButton1.setText("Add to Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel2.add(jButton1, gridBagConstraints);

        ProductsPanel.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(ProductsPanel, java.awt.BorderLayout.WEST);

        jPanel3.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(50, 35));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        btnInventory.setText("Inventory");
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });
        jPanel3.add(btnInventory);

        btnTransaction.setText("Transaction");
        btnTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactionActionPerformed(evt);
            }
        });
        jPanel3.add(btnTransaction);

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        CheckoutButton.setText("Checkout");
        CheckoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckoutButtonActionPerformed(evt);
            }
        });
        jPanel4.add(CheckoutButton);

        getContentPane().add(jPanel4, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
    
    Inventory inventoryWindow = new Inventory(service);
    inventoryWindow.setVisible(true);
    
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactionActionPerformed
    
    Transaction transactionWindow = new Transaction(service);
    transactionWindow.setVisible(true);
            
    }//GEN-LAST:event_btnTransactionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    String selectedItem = jList1.getSelectedValue();
    int quantity = (Integer) jSpinner1.getValue();
    Information[] inventory = service.getInventory();
    int count = service.getInventoryCount();
    
    if (selectedItem == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a product from the list!");
            return; 
        }
    
    for (int i = 0; i < count; i++) {
        if (inventory[i].getProductName().equals(selectedItem)) {
            double price = inventory[i].getPrice();
            double subtotal = price * quantity;

            // 1. Add to the Cart Table (UnitTable)
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) UnitTable.getModel();
            model.addRow(new Object[]{selectedItem, price, quantity, subtotal});

            // 2. Update the Total Label
            updateTotal();
            break;
        }
    }
    
    jSpinner1.setValue(1);    
    jList1.clearSelection();
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CheckoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckoutButtonActionPerformed
    
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) UnitTable.getModel();
    
    if (model.getRowCount() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Way sulod bai.");
        return;
    }
    
    for (int i = 0; i < model.getRowCount(); i++) {
        String itemName = (String) model.getValueAt(i,0);
        double price = (double) model.getValueAt(i,1);
        int qtySold = (Integer) model.getValueAt(i,2);
        service.reduceStock(itemName, qtySold);
        
        Information saleRecord = new Information(itemName, price, qtySold);
        service.addTransaction(saleRecord);
    }
    
    javax.swing.JOptionPane.showMessageDialog(this, "Checkout Successful!");
    model.setRowCount(0);
    updateTotal();
    
    }//GEN-LAST:event_CheckoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainSystem().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CartPanel;
    private javax.swing.JButton CheckoutButton;
    private javax.swing.JPanel ProductsPanel;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JPanel TotalPanel;
    private javax.swing.JTable UnitTable;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnTransaction;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JScrollPane jscrollpane1;
    // End of variables declaration//GEN-END:variables
}
